services:
  gateway.api:
    image: gateway.api
    container_name: gateway-api
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=eshop-db;Port=5432;Database=gatewaydb;Username=postgres;Password=postgres-adil-123
    depends_on:
      - eshop-db

  eshop.basket.api:
    image: eshop.basket.api
    container_name: basket-service
    build:
      context: .
      dockerfile: eShop.Basket.API/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=eshop-db;Port=5432;Database=basketdb;Username=postgres;Password=postgres-adil-123
      - ConnectionStrings__RabbitMQConnection=amqp://adils-rabbitmq:rabbitmq-adil-123@eshop-rabbitmq:5672/
    depends_on:
      eshop-db:
        condition: service_healthy
      rabbitmq:
       condition: service_started
  
  eshop.catalog.api:
    image: eshop.catalog.api
    container_name: catalog-service
    build:
      context: .
      dockerfile: eShop.Catalog.API/Dockerfile
    ports:
      - "5025:5025"
      - "7167:7167"
    environment:
      - ConnectionStrings__DefaultConnection=Host=eshop-db;Port=5432;Database=catalogdb;Username=postgres;Password=postgres-adil-123
      - ConnectionStrings__RabbitMQConnection=amqp://adils-rabbitmq:rabbitmq-adil-123@eshop-rabbitmq:5672/
    depends_on:
     eshop-db:
      condition: service_healthy
     rabbitmq:
      condition: service_started
    
    
    #  orderservice.api:
#    image: orderservice.api
#    container_name: order-service
#    build:
#      context: .
#      dockerfile: OrderService.Api/Dockerfile
#    environment:
#      - ConnectionStrings__DefaultConnection=Host=eshop-db;Port=5432;Database=ordersdb;Username=postgres;Password=postgres-adil-123
#    depends_on:
#      - eshop-db
#      - rabbitmq

  eshop-db:
    container_name: eshop-database
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres-adil-123 
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    
  rabbitmq:
    stdin_open: true
    tty: true
    container_name: eshop-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=adils-rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq-adil-123
    ports:
      - 5672:5672
      - 15672:15672
    image: rabbitmq:4-management
    
    
  redis:
    container_name: eshop-redis
    image: redis
    command: redis-server --save 120 1 --loglevel warning

networks:
  default:
    name: eshop-network
